config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "home#index"
  namespace :admin do
    get "/", to: "home#index"
    resources :users
    resources :sessions
    resources :questions
    resources :answers
    get "/signup", to: "users#new"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
  end
end

app/models/answer.rb
# frozen_string_literal: true

# class Answer
class Answer < ApplicationRecord
  belongs_to :question
  validates :text, presence: true
end

app/models/application_record.rb
# frozen_string_literal: true

# class ApplicationRecord
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
# frozen_string_literal: true

# class Question
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  validates :text, presence: true,
                   length: { minimum: 3 },
                   uniqueness: true,
                   answer: true
  accepts_nested_attributes_for :answers, allow_destroy: true
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :user
  has_many :testanswers, dependent: :destroy
  validates :score, testanswer: true
  accepts_nested_attributes_for :testanswers, allow_destroy: true
end

app/models/testanswer.rb
class Testanswer < ApplicationRecord
  belongs_to :test
  belongs_to :question
  belongs_to :answer
end

app/models/user.rb
# frozen_string_literal: true

# class User
class User < ApplicationRecord
  has_secure_password
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  enum role: { admin: 0, user: 1 }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }, if: :new_record?
  validates :role, presence: true
end

app/controllers/admin/answers_controller.rb
# frozen_string_literal: true

module Admin
  # class UsersController
  class AnswersController < ApplicationController
    def update
      @answer = Answer.find(params[:id])
      @question = @answer.question
      @question.answers.update(flag: false)
      @answer.update(flag: true)
      respond_to do |format|
        format.js
      end
    end
  end
end

app/controllers/admin/home_controller.rb
# frozen_string_literal: true

module Admin
  # class HomeController
  class HomeController < ApplicationController
    def index; end
  end
end

app/controllers/admin/questions_controller.rb
# frozen_string_literal: true

module Admin
  # class QuestionsController
  class QuestionsController < ApplicationController
    def index
      @questions = Question.order(:id).page(params[:page]).per(10)
    end

    def new
      @question = Question.new
      4.times { @question.answers.build }
    end

    def edit
      @question = Question.find(params[:id])
    end

    def create
      @question = Question.new(question_params)
      if @question.save
        redirect_to admin_questions_path
      else
        render "new"
      end
    end

    def update
      @question = Question.find(params[:id])

      if @question.update(question_params)
        redirect_to admin_questions_path
      else
        render "edit"
      end
    end

    def destroy
      @question = Question.find(params[:id])
      @question.destroy

      redirect_to admin_questions_path
    end

    private

    def question_params
      params.require(:question).permit(:text, answers_attributes: %i[id text _destroy flag])
    end
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

module Admin
  # class SessionsController
  class SessionsController < ApplicationController
    def new; end

    def create
      user = User.admin.find_by(email: params[:session][:email].downcase)
      if user&.authenticate(params[:session][:password])
        login(user)
      else
        login_error(user)
      end
    end

    def destroy
      log_out if logged_in? # only log out if a user is currently logged in
      redirect_to root_url
    end

    private

    def show_message(user)
      user&.user? ? "Not admin" : "Invalid email/password combination"
    end

    def login(user)
      log_in user
      redirect_to admin_path
    end

    def login_error(user)
      flash.now[:danger] = show_message user
      render "new"
    end
  end
end

app/controllers/admin/tests_controller.rb
# frozen_string_literal: true

module Admin
  # class UsersController
  class TestsController < ApplicationController
    def update
# ------------------------------------------------------------------
      @questions = Question.where(id: params[:question])
# ------------------------------------------------------------------
      unless @questions.nil?
        @test = Test.create(user_id: current_user.id, score: params[:score])
        @questions.each  do | question |
          question.answers.each  do | answer |
            @testanswer = Testanswer.create(test_id: @test.id, question_id: question.id, answer_id: answer.id)
          end
        end
      end
# -----------------------------------------------------------------
    end

  end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

# class Admin::UsersController
module Admin
  # Controller for Users
  class UsersController < ApplicationController
    before_action :find_user, only: %i[edit update destroy]

    def index
      @users = User.order(:id).page(params[:page]).per(10)
    end

    def new
      @user = User.new
    end

    def edit; end

    def create
      @user = User.new(user_params)
      if @user.save
        redirect_to admin_users_path
      else
        render :new
      end
    end

    def update
      if @user.update(user_params)
        redirect_to admin_users_path
      else
        render :edit
      end
    end

    def destroy
      @user.destroy
      respond_to do |format|
        format.js
      end
    end

    private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :role)
    end

    def find_user
      @user = User.find(params[:id])
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# class ApplicationController
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# class HomeController
class HomeController < ApplicationController
  def index
    if !logged_in?
      @questions = Question.all.sample(3)
    end
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

# class SessionsController
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.user.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      login(user)
    else
      login_error(user)
    end
  end

  def destroy
    log_out if logged_in? # only log out if a user is currently logged in
    redirect_to root_url
  end

  private

  def show_message(user)
    user&.user? ? "Not admin" : "Invalid email/password combination"
  end

  def login(user)
    log_in user
    redirect_to root_path
  end

  def login_error(user)
    flash.now[:danger] = show_message user
    render "new"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# module ApplicationHelper
module ApplicationHelper
  # Returns the full title
  def full_title(page_title = "")
    base_title = "Ruby on Rails Question Answer"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

# module SessionsHelper
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admin/answers/_answer.html.erb
<div id="correct_form-<%= answer.id %>">
  <% if answer.flag? %>
      <%= render 'uncorrect',answer: answer %>
  <% else %>
      <%= render 'correct',answer: answer %>
  <% end %>
</div>

app/views/admin/answers/update.js.erb
<% @question.answers.each do |answer| %>
  $("#correct_form-<%= answer.id %>").html("<%= escape_javascript(render('admin/questions/correct', answer: answer)) %>");
<% end %>
$("#correct_form-<%= @answer.id %>").html("<%= escape_javascript(render('admin/questions/uncorrect', answer: @answer)) %>");

app/views/admin/home/index.html.erb
<% if logged_in? %>
   <div class="center jumbotron">
     <h1>Welcome to the Admin Home Page</h1>

     <h2>
       This is my admin home page for the
       <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
       sample application.
     </h2>

     <%= link_to "Welcome back #{current_user.name}!", edit_admin_user_path(current_user), class: "btn btn-lg btn-primary" %>
     <%= link_to "User management", admin_users_path, class: "btn btn-lg btn-primary" %>
     <%= link_to "Question management", admin_questions_path, class: "btn btn-lg btn-primary" %>
   </div>

<% else %>
   <div class="center jumbotron">
     <h1>Welcome to the Sample App</h1>

     <h2>
       This is my home page for the
       <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
       sample application.
     </h2>

     <%= link_to "Sign up now!", admin_signup_path, class: "btn btn-lg btn-primary" %>
   </div>

<% end %>

app/views/admin/questions/_correct.html.erb
<h1><%= answer.text %></h1>
<%= form_with model: [:admin, answer] do |form| %>
  <div><%= hidden_field_tag :id, answer.id %></div>
  <div><%= hidden_field_tag :flag, answer.flag %></div>
  <%= form.submit "Uncorrect", data: { disable_with: "Please wait..." }, class: "btn" %>
<% end %>

app/views/admin/questions/_form.html.erb
<%= form_with model: [:admin, @question] , local: true do |form| %>

  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@question.errors.count, "error") %> prohibited
        this question from being saved:
      </h2>
      <ul>
        <% @question.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :'Question' %><br>
    <%= form.text_area :text %>
  </p>

  <strong>Answers:</strong>
  <ul>
    <%= form.fields_for :answers do |answers_form| %>
      <p>
        <%= answers_form.check_box :flag %>
      </p>
      <p>
        <%= answers_form.label :"Answer #{answers_form.index + 1}" %><br>
        <%= answers_form.text_area :text %>
      </p>
    <% end %>
  </ul>

  <p>
    <%= form.submit button_text %>
  </p>

<% end %>

app/views/admin/questions/_uncorrect.html.erb
<h1><strong>
  <%= answer.text %>
</strong></h1>
<%= button_tag "Correct", class: "btn btn-primary btn-block", disabled: true %>

app/views/admin/questions/edit.html.erb
<h1>Edit question</h1>

<%= render 'form', button_text: "Update question" %>

<%= link_to 'Back', admin_question_path %>

app/views/admin/questions/index.html.erb
<h1>Listing Questions</h1>
<%= link_to 'New question', new_admin_question_path %>
<%= paginate @questions %>
<%= page_entries_info @questions, entry_name: 'item' %>
<table class="table">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Question</th>
      <th scope="col"></th>
      <th scope="col"></th>
      <th scope="col">Answer</th>
      <th scope="col">Correct Answer</th>
    </tr>
  </thead>

  <% @questions.each do |question| %>
  <tr>
    <td><%= question.id %></td>
    <td><%= question.text %></td>
    <td><%= link_to 'Show', admin_question_path(question) %></td>
    <td><%= link_to 'Edit', edit_admin_question_path(question) %></td>
    <td><%= link_to 'Delete', admin_question_path(question),
              method: :delete,
              data: { confirm: 'You sure?' } %></td>
    <td><%= question.answers.map{|a| a.text}.join(", ") if question.answers.present? %></td>
    <td><%= question.answers.find_by(flag: true)&.text if question.answers.present? %></td>
  </tr>
  <% end %>
</table>
<br>
<%= link_to 'Back', admin_path %>

app/views/admin/questions/new.html.erb
<h1>New question</h1>

<%= render 'form', button_text: "Create question" %>

<%= link_to 'Back', admin_questions_path %>

app/views/admin/questions/show.html.erb
<h1>Show question</h1>
<strong>Question:</strong>
  <h1><%= @question.text %>
  <%= link_to 'Delete', admin_question_path(@question),
              method: :delete,
              data: { confirm: 'You sure?' } %><br></h1>
<strong>Answers:</strong><br>
<%= render @question.answers %>
<%= link_to 'Edit', edit_admin_question_path(@question) %> |
<%= link_to 'Back', admin_questions_path %>

app/views/admin/users/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with model: [:admin, @user] , local: true do |form| %>

      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@user.errors.count, "error") %> prohibited
            this user from being saved:
          </h2>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control" %>

      <%= form.label :email %>
      <%= form.email_field :email, class: "form-control" %>

      <% if action_name == 'new' or action_name == 'create' %>
        <%= form.label :password %>
        <%= form.password_field :password, class: "form-control" %>
        <%= form.label :password_confirmation, "Confirmation" %>
        <%= form.password_field :password_confirmation, class: 'form-control' %>
      <% end %>

      <%= form.label :role %>
      <%= form.select(:role, User.roles.keys.map { |w| [w.humanize, w] }, {include_blank: "Select"}, {class: "form-control"} ) %>

      <%= form.submit button_text, class: "btn btn-primary"%>

    <% end %>
  </div>
</div>

app/views/admin/users/destroy.js.erb
$('.user-<%= @user.id %>').closest('tr').remove();

app/views/admin/users/edit.html.erb
<h1>Edit user</h1>

<%= render 'form', button_text: "Update User" %>

<%= link_to 'Back', admin_users_path %>

app/views/admin/users/index.html.erb
<h1>Listing users</h1>
<%= link_to 'New user', new_admin_user_path %>
<%= paginate @users %>
<%= page_entries_info @users, entry_name: 'item' %>
<table class="table">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <!-- <th scope="col">Pasword</th> -->
      <th scope="col">Role</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <% @users.order(:id).each do |user| %>
    <tr>
      <td><%= user.id %></td>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <!-- <td><%= user.password_digest %></td> -->
      <td><%= user.role %></td>
      <td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
      <td>
        <% if current_user.id != user.id %>
        <%= link_to 'Delete', admin_user_path(user),
                remote: true,
                method: :delete,
                data: { confirm: 'You sure?' },
                class: "user-#{user.id}" %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>
<br>
<%= link_to 'Back', admin_path %>

app/views/admin/users/new.html.erb
<h1>New user</h1>

<%= render 'form', button_text: "Create User" %>

<%= link_to 'Back', admin_users_path %>

app/views/home/_quiz.html.erb
<div class="grid">
    <div id="quiz">
        <h1>Quiz</h1>
        <hr style="margin-bottom: 20px">

        <p id="question"></p>

        <div class="buttons">
            <button id="btn0"><span id="choice0"></span></button>
            <button id="btn1"><span id="choice1"></span></button>
            <button id="btn2"><span id="choice2"></span></button>
            <button id="btn3"><span id="choice3"></span></button>
        </div>

        <footer>
            <p id="progress">Question x of y</p>
        </footer>
    </div>
</div>

<script> // quiz.js
    function Quiz(questions) {
    this.score = 0;
    this.questions = questions;
    this.questionIndex = 0;
    }
    Quiz.prototype.getQuestionIndex = function() {
        return this.questions[this.questionIndex];
    }
    Quiz.prototype.guess = function(answer) {
        if(this.getQuestionIndex().isCorrectAnswer(answer)) {
            this.score++;
        }
        this.questionIndex++;
    }
    Quiz.prototype.isEnded = function() {
        return this.questionIndex === this.questions.length;
    }
</script>
<script> // question.js
    function Question(text, choices, answer) {
    this.text = text;
    this.choices = choices;
    this.answer = answer;
    }
    Question.prototype.isCorrectAnswer = function(choice) {
        return this.answer === choice;
    }
</script>
<script> // app.js
    function populate() {
    if(quiz.isEnded()) {
        showScores();
    }
    else {
        // show question
        var element = document.getElementById("question");
        element.innerHTML = quiz.getQuestionIndex().text;
        // show options
        var choices = quiz.getQuestionIndex().choices;
        for(var i = 0; i < choices.length; i++) {
            var element = document.getElementById("choice" + i);
            element.innerHTML = choices[i];
            guess("btn" + i, choices[i]);
        }
        showProgress();
    }
    };
    function guess(id, guess) {
        var button = document.getElementById(id);
        button.onclick = function() {
            quiz.guess(guess);
            populate();
        }
    };
    function showProgress() {
        var currentQuestionNumber = quiz.questionIndex + 1;
        var element = document.getElementById("progress");
        element.innerHTML = "Question " + currentQuestionNumber + " of " + quiz.questions.length;
    };
    function showScores() {
        var gameOverHTML = "<h1>Result</h1>";
        gameOverHTML += "<h2 id='score'> Your scores: " + quiz.score + "/" + quiz.questions.length + "</h2>";

        var element = document.getElementById("quiz");
        element.innerHTML = gameOverHTML;

        // Send POST to /admin/tests and tests#updatey
        var question = [
          <% @questions.each do |q| %>
            "<%= q.id %>",
          <% end %>
        ];
        $.post("/admin/tests",
            {
                score: quiz.score,
                questions: quiz.questions,
                question: question
            });
    };
    // create questions
    var questions = [
      <% @questions.each do |q| %>
        new Question("<%= q.text %>", ["<%= q.answers.first.text %>", "<%= q.answers.second.text %>","<%= q.answers.third.text %>", "<%= q.answers.fourth.text %>"], "<%= q.answers.find_by(flag: true)&.text if q.answers.present? %>"),
      <% end %>
    ];
    var question = [
      <% @questions.each do |q| %>
        new Question("<%= q.id %>"),
      <% end %>
    ];
    // create quiz
    var quiz = new Quiz(questions);
    // display quiz
    populate();
</script>

app/views/home/index.html.erb
<% if logged_in? %>



<div class="center jumbotron">
     <h1>Welcome to the Question Answer</h1>

     <h2>
       This is my admin home page for the
       <a href="http://www.railstutorial.org/">Question Answer</a>
       sample application.
     </h2>

     <%= link_to "Login and Play", login_path, class: "btn btn-lg btn-primary" %>
   </div>

<% else %>

<%= render 'quiz' %>

<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="#">Question Answer</a>
    by <a href="#">Memphis Depay</a>
  </small>
  <nav>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
 <div class="container">
   <%= link_to "sample app", root_path, id: "logo" %>
   <nav>
     <ul class="nav navbar-nav navbar-right">
       <% if logged_in? && (controller_path == 'admin/home' || controller_path == 'admin/users' || controller_path == 'admin/questions')%>
         <li><%= link_to "#{current_user.name}", edit_admin_user_path(current_user) %></li>
         <li><%= link_to "Log out", admin_logout_path, method: :delete %></li>
       <% else %>
         <li><%= link_to "Signup", admin_signup_path %></li>
         <li><%= link_to "Log in", admin_login_path %></li>
       <% end %>
     </ul>
   </nav>
 </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
   <head>
      <title><%= full_title(yield(:title)) %></title>
      <%= csrf_meta_tags %>
      <%= stylesheet_link_tag    'application', media: 'all',
      'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <%= render 'layouts/shim' %>
   </head>
   <body>
      <%= render 'layouts/header' %>
      <div class="container">
         <% flash.each do |message_type, message| %>
         <div class="alert alert-<%= message_type %>"><%= message %></div>
         <% end %>
         <%= yield %>
         <%= render 'layouts/footer' %>
         <%= debug(params) if Rails.env.development? %>
      </div>
   </body>
</html>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>